//
//  NoteDetailView.swift
//  NoteWorthy
//
//  Created by Mohamed Fiyaz on 13/01/25.
//

import SwiftUI

struct NoteDetailView: View {
    @Environment(\.dismiss) private var dismiss
    @ObservedObject var noteService: NoteService
    let note: Note
    @State private var editedTitle: String
    @State private var editedContent: String
    @State private var editedColor: String
    @State private var editedIsFavorite: Bool
    @State private var showingDiscardAlert = false
    @State private var showingDeleteAlert = false
    @State private var showingQAGeneration = false
    
    let colors = [
        "#F8F8F8", // Light Gray
        "#FFFBF2", // Light Cream
        "#FFE4E1", // Misty Rose
        "#E6F7FF", // Light Sky Blue
        "#E5EAF5", // Lavender Blue
        "#F2F2D9", // Light Pastel Yellow
        "#DCE9E2", // Mint Green
        "#EADFF7", // Light Lilac
        "#D7CCC8", // Light Taupe
        "#C8E6C9", // Pale Green
        "#B2DFDB", // Aquamarine
        "#B3CDE3"  // Dusty Blue
    ]
    
    init(note: Note, noteService: NoteService) {
        self.note = note
        self.noteService = noteService
        _editedTitle = State(initialValue: note.title)
        _editedContent = State(initialValue: note.content)
        _editedColor = State(initialValue: note.colorHex)
        _editedIsFavorite = State(initialValue: note.isFavorite)
    }
    
    var hasChanges: Bool {
        editedTitle != note.title ||
        editedContent != note.content ||
        editedColor != note.colorHex ||
        editedIsFavorite != note.isFavorite
    }
    
    var body: some View {
        Form {
            Section {
                TextField("Title", text: $editedTitle)
                TextEditor(text: $editedContent)
                    .frame(height: 200)
            } header: {
                HStack {
                    Text("Note Details")
                    Spacer()
                    Image(systemName: editedIsFavorite ? "star.fill" : "star")
                        .foregroundColor(editedIsFavorite ? .yellow : .gray)
                        .onTapGesture {
                            editedIsFavorite.toggle()
                        }
                }
            }
            
            Section(header: Text("Note Color")) {
                LazyVGrid(columns: [GridItem(.adaptive(minimum: 44))], spacing: 10) {
                    ForEach(colors, id: \.self) { color in
                        Circle()
                            .fill(Color(hex: color))
                            .frame(width: 44, height: 44)
                            .overlay(
                                Circle()
                                    .stroke(color == editedColor ? Color.blue : Color.clear, lineWidth: 2)
                            )
                            .onTapGesture {
                                editedColor = color
                            }
                    }
                }
            }
            
            Section {
                if note.isAIGenerated {
                    HStack {
                        Image(systemName: "sparkle")
                            .foregroundColor(.blue)
                        Text("This note was generated by Iris")
                            .foregroundColor(Color(.systemGray))
                    }
                }
                // Q&A Generation Button
                Button(action: { showingQAGeneration = true }) {
                    HStack {
                        Image(systemName: "eye")
                        Text("Generate Q&As")
                    }
                    .foregroundColor(Color(#colorLiteral(red: 0.553298533, green: 0.7063716054, blue: 0.8822532296, alpha: 1)))
                }
                
                // Delete Note Button
                Button(role: .destructive, action: { showingDeleteAlert = true }) {
                    HStack {
                        Image(systemName: "trash")
                        Text("Delete Note")
                    }
                }
            }
        }
        .navigationTitle("Edit Note")
        .toolbar {
            ToolbarItem(placement: .navigationBarLeading) {
                Button("Cancel") {
                    if hasChanges {
                        showingDiscardAlert = true
                    } else {
                        dismiss()
                    }
                }
            }
            ToolbarItem(placement: .navigationBarTrailing) {
                Button("Save") {
                    saveChanges()
                }
                .disabled(!hasChanges)
            }
        }
        .alert("Discard Changes?", isPresented: $showingDiscardAlert) {
            Button("Discard", role: .destructive) { dismiss() }
            Button("Keep Editing", role: .cancel) { }
        }
        .alert("Delete Note", isPresented: $showingDeleteAlert) {
            Button("Cancel", role: .cancel) { }
            Button("Delete", role: .destructive) {
                noteService.deleteNote(note)
                dismiss()
            }
        } message: {
            Text("Are you sure you want to delete this note?")
        }
        .sheet(isPresented: $showingQAGeneration) {
            GenerateQAView(note: note)
        }
    }
    
    private func saveChanges() {
        var updatedNote = note
        updatedNote.title = editedTitle
        updatedNote.content = editedContent
        updatedNote.colorHex = editedColor
        updatedNote.isFavorite = editedIsFavorite
        noteService.updateNote(updatedNote)
        dismiss()
    }
}
